version: "3"

services:
  traefik:
    volumes:
      - ./docker/traefik/certs:/etc/traefik/certs
      - ./docker/traefik/config.yml:/etc/traefik/config.yml:ro
      - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro

  webserver:
    image: nginx:1.20-alpine
    labels:
      - "traefik.http.routers.webserver.rule=Host(`ppiedufest.docker.localhost`)"
    volumes:
      - .:/var/www:ro
      - ./docker/webserver/conf.d:/etc/nginx/conf.d:ro

  app:
    image: ppi-edufest/app:latest
    entrypoint: ["app-entrypoint.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      SERVICE_TAGS: dev
      DB_HOST:
      DB_DATABASE:
      DB_USERNAME:
      DB_PASSWORD:

  database:
    environment:
      SERVICE_TAGS: dev
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.docker.localhost`)"

networks:
  network-1:
    driver: bridge
