version: "3"

services:
  watchtower:
    image: containrrr/watchtower
    command: ["--interval", "300"]
    container_name: ppi-edufest-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik:2.5
    restart: unless-stopped
    container_name: ppi-edufest-traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - no-new-privileges:true

  webserver:
    restart: unless-stopped
    container_name: ppi-edufest-webserver
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.tls=true"
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      app:
        condition: service_started
    healthcheck:
      test:
        [
          "CMD",
          "service",
          "nginx",
          "status",
          "||",
          "exit",
          "1"
        ]
      timeout: 10s
      retries: 6

  app:
    restart: unless-stopped
    command: ["php-fpm"]
    working_dir: /var/www
    container_name: ppi-edufest-app
    depends_on:
      database:
        condition: service_healthy
    environment:
      SERVICE_NAME: app

  database:
    image: mariadb:10.6
    restart: unless-stopped
    container_name: ppi-edufest-database
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      SERVICE_NAME: db
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "${DB_USERNAME}",
          "-p${DB_PASSWORD}",
        ]
      timeout: 10s
      retries: 6

  phpmyadmin:
    image: phpmyadmin:5.1
    restart: unless-stopped
    container_name: ppi-edufest-phpmyadmin
    depends_on:
      database:
        condition: service_healthy
    environment:
      PMA_HOST: database

volumes:
  dbdata:
    driver: local
