version: "3"

services:
  app:
    container_name: ppi-edufest-app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    expose:
      - "9000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - network-1

  webserver:
    container_name: ppi-edufest-webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      app:
        condition: service_started
      database:
        condition: service_healthy
    networks:
      - network-1

  database:
    image: mariadb:10.6
    container_name: ppi-edufest-database
    restart: unless-stopped
    expose:
      - "3306"
    environment:
      SERVICE_NAME: db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      timeout: 10s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - network-1

  phpmyadmin:
    image: phpmyadmin:5.1
    container_name: ppi-edufest-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - network-1
    environment:
      PMA_HOST: database
    depends_on:
      database:
        condition: service_healthy

networks:
  network-1:
    driver: bridge

volumes:
  dbdata:
    driver: local
