version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppi-edufest-app
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www
      # - apppublicdata:/var/www/public
    networks:
      - ppi-edufest-network

  webserver:
    # build:
    #   context: ./docker/webserver
    #   dockerfile: Dockerfile
    image: nginx:1.20-alpine
    container_name: ppi-edufest-webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/webserver/conf.d/:/etc/nginx/conf.d/
      - .:/var/www:ro
    networks:
      - ppi-edufest-network

  database:
    image: mariadb:10.6
    container_name: ppi-edufest-database
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_NAME: db
      SERVICE_TAGS: prod
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ppi-edufest-network

  phpmyadmin:
    image: phpmyadmin:5.1
    container_name: ppi-edufest-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - ppi-edufest-network
    environment:
      PMA_ARBITRARY: 1

networks:
  ppi-edufest-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
