http:
  routers:
    traefik:
      rule: "Host(`traefik.mangkoran.xyz`)"
      service: "api@internal"
      tls:
        domains:
          - main: "mangkoran.xyz"
            sans:
              - "*.mangkoran.xyz"

tls:
  certificates:
    - certFile: "/etc/traefik/certs/local-cert.pem"
      keyFile: "/etc/traefik/certs/local-key.pem"
